# Site settings
title: Test Dimension
email: contact@tony.pp.ua
description: A fully responsive site template.
baseurl: "/dimension-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/tonywww
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed
